import { TrackedJet } from "@/types/aircraft";

// Known private jets of high-profile individuals
// ICAO24 codes are the aircraft transponder identifiers
export const trackedJets: TrackedJet[] = [
  // Tech Billionaires
  {
    icao24: "a835af",
    name: "Gulfstream G650ER",
    owner: "Elon Musk",
    type: "GLF6",
    category: "tech",
    description: "Elon Musk's primary jet - often shuttles between Austin, Hawthorne, and Fremont",
  },
  {
    icao24: "a0f337",
    name: "Gulfstream G650ER",
    owner: "Jeff Bezos",
    type: "GLF6",
    category: "tech",
    description: "Bezos' jet - frequently seen in Seattle, NYC, and Van Horn, TX",
  },
  {
    icao24: "a7c80e",
    name: "Gulfstream G650",
    owner: "Mark Zuckerberg",
    type: "GLF5",
    category: "tech",
    description: "Zuck's jet - usually between Menlo Park, Kauai, and NYC",
  },
  {
    icao24: "a184d0",
    name: "Bombardier Global 7500",
    owner: "Bill Gates",
    type: "GL7T",
    category: "tech",
    description: "Gates' jet - often in Seattle, NYC, and humanitarian mission locations",
  },
  {
    icao24: "a88e9f",
    name: "Gulfstream G650ER",
    owner: "Larry Ellison",
    type: "GLF6",
    category: "tech",
    description: "Oracle founder - frequently between Lanai, Hawaii and California",
  },
  {
    icao24: "a9b67c",
    name: "Gulfstream G650",
    owner: "Larry Page",
    type: "GLF5",
    category: "tech",
    description: "Google co-founder - Palo Alto, NYC, and island destinations",
  },
  {
    icao24: "a9b67d",
    name: "Gulfstream G650",
    owner: "Sergey Brin",
    type: "GLF5",
    category: "tech",
    description: "Google co-founder - similar routes to Page",
  },
  {
    icao24: "aa7a4f",
    name: "Dassault Falcon 7X",
    owner: "Tim Cook",
    type: "FA7X",
    category: "tech",
    description: "Apple CEO - Cupertino and business destinations",
  },
  {
    icao24: "a63ab8",
    name: "Gulfstream G650ER",
    owner: "Jensen Huang",
    type: "GLF6",
    category: "tech",
    description: "NVIDIA CEO - Santa Clara and AI conference circuit",
  },
  
  // Political / Business
  {
    icao24: "a99bbc",
    name: "Boeing 757",
    owner: "Donald Trump",
    type: "B752",
    category: "political",
    description: "Trump Force One - Mar-a-Lago, Bedminster, and rally locations",
  },
  {
    icao24: "a9e60f",
    name: "Cessna Citation X",
    owner: "Warren Buffett",
    type: "C750",
    category: "business",
    description: "Berkshire Hathaway - Omaha and acquisition targets",
  },
  {
    icao24: "a44d6c",
    name: "Gulfstream G550",
    owner: "Michael Bloomberg",
    type: "GLF5",
    category: "business",
    description: "Bloomberg LP - NYC and London primarily",
  },
  {
    icao24: "a37d95",
    name: "Bombardier Global 6000",
    owner: "Ken Griffin",
    type: "GLEX",
    category: "business",
    description: "Citadel - Chicago, Miami, and financial centers",
  },
  {
    icao24: "a7c2f1",
    name: "Gulfstream G650",
    owner: "Carl Icahn",
    type: "GLF5",
    category: "business",
    description: "Icahn Enterprises - NYC and activist investor targets",
  },
  {
    icao24: "a11aa9",
    name: "Gulfstream G650ER",
    owner: "Stephen Schwarzman",
    type: "GLF6",
    category: "business",
    description: "Blackstone - NYC and deal locations worldwide",
  },
  {
    icao24: "a4b96e",
    name: "Bombardier Global 7500",
    owner: "Jamie Dimon",
    type: "GL7T",
    category: "business",
    description: "JPMorgan Chase - NYC and regulatory meetings",
  },
  {
    icao24: "a648cf",
    name: "Gulfstream G650",
    owner: "Ray Dalio",
    type: "GLF5",
    category: "business",
    description: "Bridgewater - Westport, CT and macro research trips",
  },
  
  // Government / Indicators
  {
    icao24: "ae4ec0",
    name: "VC-25A (Air Force One)",
    owner: "POTUS",
    type: "B742",
    category: "government",
    description: "Air Force One - SAM callsign when President aboard",
  },
  {
    icao24: "ae4ec1",
    name: "VC-25A (Air Force One Backup)",
    owner: "POTUS",
    type: "B742",
    category: "government",
    description: "Backup AF1 - travels with primary",
  },
  {
    icao24: "ae4e8d",
    name: "C-32A (Air Force Two)",
    owner: "VPOTUS",
    type: "B752",
    category: "government",
    description: "Air Force Two - Vice President transport",
  },
  {
    icao24: "ae4e8c",
    name: "C-40B (SAM Fox)",
    owner: "USAF",
    type: "B737",
    category: "government",
    description: "VIP transport - Cabinet and high officials",
  },
  {
    icao24: "ae4e9e",
    name: "C-37A (Gulfstream V)",
    owner: "USAF",
    type: "GLF5",
    category: "government",
    description: "VIP transport - Generals and diplomats",
  },
  {
    icao24: "ae4ebd",
    name: "E-4B Nightwatch",
    owner: "USAF",
    type: "B742",
    category: "government",
    description: "Doomsday Plane - airborne command post",
  },
  {
    icao24: "ae4e97",
    name: "E-6B Mercury",
    owner: "USN",
    type: "B762",
    category: "government",
    description: "Looking Glass - nuclear command and control",
  },
  {
    icao24: "ae4b00",
    name: "C-17 Globemaster III",
    owner: "USAF",
    type: "C17",
    category: "government",
    description: "Heavy transport - watch for unusual destinations",
  },
  {
    icao24: "ae4b01",
    name: "C-17 Globemaster III",
    owner: "USAF",
    type: "C17",
    category: "government",
    description: "Heavy transport - watch for unusual destinations",
  },
  {
    icao24: "ae4b02",
    name: "C-17 Globemaster III",
    owner: "USAF",
    type: "C17",
    category: "government",
    description: "Heavy transport - watch for unusual destinations",
  },
  {
    icao24: "ae4cdd",
    name: "KC-135 Stratotanker",
    owner: "USAF",
    type: "K35R",
    category: "government",
    description: "Aerial refueling - often precedes operations",
  },
  {
    icao24: "ae4cde",
    name: "KC-135 Stratotanker",
    owner: "USAF",
    type: "K35R",
    category: "government",
    description: "Aerial refueling - often precedes operations",
  },
  {
    icao24: "ae4cdf",
    name: "KC-135 Stratotanker",
    owner: "USAF",
    type: "K35R",
    category: "government",
    description: "Aerial refueling - often precedes operations",
  },
  {
    icao24: "ae54be",
    name: "RC-135 Rivet Joint",
    owner: "USAF",
    type: "R135",
    category: "government",
    description: "SIGINT aircraft - monitors communications",
  },
  {
    icao24: "ae54bf",
    name: "RC-135 Rivet Joint",
    owner: "USAF",
    type: "R135",
    category: "government",
    description: "SIGINT aircraft - monitors communications",
  },
  {
    icao24: "ae01d4",
    name: "P-8 Poseidon",
    owner: "USN",
    type: "P8",
    category: "government",
    description: "Maritime patrol - submarine hunter",
  },
  {
    icao24: "ae01d5",
    name: "P-8 Poseidon",
    owner: "USN",
    type: "P8",
    category: "government",
    description: "Maritime patrol - submarine hunter",
  },
  {
    icao24: "ae01d6",
    name: "P-8 Poseidon",
    owner: "USN",
    type: "P8",
    category: "government",
    description: "Maritime patrol - submarine hunter",
  },
  {
    icao24: "ae680a",
    name: "RQ-4 Global Hawk",
    owner: "USAF",
    type: "Q4",
    category: "government",
    description: "Surveillance drone - high altitude recon",
  },
  {
    icao24: "ae680b",
    name: "RQ-4 Global Hawk",
    owner: "USAF",
    type: "Q4",
    category: "government",
    description: "Surveillance drone - high altitude recon",
  },
  {
    icao24: "ae5421",
    name: "U-2 Dragon Lady",
    owner: "USAF",
    type: "U2",
    category: "government",
    description: "High altitude reconnaissance - watch near hotspots",
  },
  {
    icao24: "ae5422",
    name: "U-2 Dragon Lady",
    owner: "USAF",
    type: "U2",
    category: "government",
    description: "High altitude reconnaissance - watch near hotspots",
  },
  {
    icao24: "ae1165",
    name: "WC-135 Constant Phoenix",
    owner: "USAF",
    type: "W135",
    category: "government",
    description: "Nuclear sniffer - detects radiation",
  },
];

// Create a lookup map for fast access
export const jetLookup = new Map(trackedJets.map(jet => [jet.icao24.toLowerCase(), jet]));
